### ISSUE TITLE
The resolution of input images

### ISSUE THREAD

**Issue by Lizhuoling** [OpenDriveLab/TopoNet#1]
Hi, huge congratulations to your great work!
I have read the paper carefully, but do not understand the resolution of the input images. In the paper, you say that the input resolution is 2048*1550 and the front view image is cropped to 1550*1550, and then they are resized by a factor 0.5.

So, the input resolution for the front view is 775*775, and the other views are 1024 * 775? Since their input resolutions are different, so they are input to the backbones separately? Or the front view is padded in the same resolution as the other views and input to the backbone in a single batch?

Anyway, what are the resolutions of the various view images input to the backbone?

**Comment by sephyli** [comment]
Dear @Lizhuoling,

Thank you for your kind words and for bringing up this issue. We apologize for any confusion caused by the input resolutions mentioned in our paper.

To clarify, we crop the front-view image to 775 * 775 and resize the other views to 1024 * 775. Then, all input images are padded to 1024 * 800 to ensure consistency in the feature maps generated by the backbone.

Regarding your question about whether the input images are processed separately or in a single batch, we input all the images to the backbone in a single batch.

We hope this clears up any confusion you may have had. If you have any further questions or concerns, please do not hesitate to reach out to us.

Best regards,
Tianyu Li

**Comment by sephyli** [comment]
Yes, cropping off a portion of pixels can result in traffic elements being invisible in the front view. The cropped traffic elements account for less than 1% of the dataset, but it does affect the detection performance of traffic elements. It's important to address this issue and find a solution that balances computational costs and performance losses.

In this situation, there are a few potential solutions:
- Padding the front-view image and other perspective images to 2048*2048
- Transposing the front view image
- Resizing the front view image to match other images
However, these methods can lead to higher computational costs or potential performance losses.

In the end, we chose a compromise solution of crop and resize, and we tried to crop as much of the lower part as possible to retain more sky pixels.
