### ISSUE TITLE
reference_points update in the TopoNetSGNNDecoder

### ISSUE THREAD

**Issue by Catchip** [OpenDriveLab/TopoNet#22]
Hello, I would like to ask some questions regarding code. From my understanding, in the SGGDecoder, the reference points should be continuously updated with the layers, as implemented in deformable detr or maptr. However, I don't seem to see any reference point updates in the code. Is there something I am misunderstanding?
```python
for lid, layer in enumerate(self.layers):
            reference_points_input = reference_points[..., :2].unsqueeze(
                2)  # BS NUM_QUERY NUM_LEVEL 2
            output = layer(
                output,
                *args,
                reference_points=reference_points_input,
                key_padding_mask=key_padding_mask,
                te_query=te_feats[lid],
                te_cls_scores=te_cls_scores[lid],
                lclc_adj=prev_lclc_adj,
                lcte_adj=prev_lcte_adj,
                **kwargs)
            output = output.permute(1, 0, 2)

            lclc_rel_out = lclc_branches[lid](output, output)
            lclc_rel_adj = lclc_rel_out.squeeze(-1).sigmoid()
            prev_lclc_adj = lclc_rel_adj.detach()

            lcte_rel_out = lcte_branches[lid](output, te_feats[lid])
            lcte_rel_adj = lcte_rel_out.squeeze(-1).sigmoid()
            prev_lcte_adj = lcte_rel_adj.detach()

            output = output.permute(1, 0, 2)

            if self.return_intermediate:
                intermediate.append(output)
                intermediate_reference_points.append(reference_points)
                intermediate_lclc_rel.append(lclc_rel_out)
                intermediate_lcte_rel.append(lcte_rel_out)

        if self.return_intermediate:
            return torch.stack(intermediate), torch.stack(
                intermediate_reference_points), torch.stack(
                intermediate_lclc_rel), torch.stack(
                intermediate_lcte_rel)

        return output, reference_points, lclc_rel_out, lcte_rel_out
```

**Comment by sephyli** [comment]
Thanks for your question. 

We intend to do this and mentioned this in Page. 6 of the newest arxiv version, "Notably, the reference points will remain unchanged across different layers."

This is because in centerline perception, refining the reference point through prediction can lead to certain instabilities. Unlike MapTR, we use instance queries, and for polyline instances, options such as the midpoint, gravity center, or start point are typically used to update the reference point. Unfortunately, these choices result in performance degradation. We attribute this to the fact that detecting centerlines requires more global information. Restricting the feature scope to specific local areas brings no benefit, especially for longer centerlines.

To address this issue, we made improvements in LaneSegNet, and further discussions can be found in the LaneSegNet paper.
