### ISSUE TITLE
About the performance

### ISSUE THREAD

**Issue by wudongming97** [OpenDriveLab/TopoNet#7]
Hi, thanks for releasing the code!
But the performance in Table is different from the log output:
**From log file:**
Epoch(val) [24][601]	OpenLane-V2 Score: 0.3483, DET_l: 0.28414633870124817, DET_t: 0.4501965641975403, TOP_ll: 0.0415, TOP_lt: 0.2072
**From Table:**
| **TopoNet**  | ResNet-50 |  24   |    **28.5**     |     **4.1**      |    **48.1**     |     **20.8**     | **35.6** |

**Comment by sephyli** [comment]
The result in table is obtained from the paper, which was trained using an earlier codebase. The **inconsistency**, mainly observed in **DET<sub>t</sub>**, may be due to the inherent randomness in the convergence process, or the lack of consistency between codebases, configs, and other factors.
We will check the code and response you lately.

**Comment by sephyli** [comment]
We apologize for the inconvenience caused due to an inconsistency in our codebase. This issue has been resolved in the latest [commit](https://github.com/OpenDriveLab/TopoNet/commit/4c2317e64af35b1890031dd5d9b264c500571a4d), where both the model and log have been updated and re-uploaded.

Here are the performance metrics of the revised model:
| DET<sub>l</sub> | TOP<sub>ll</sub> | DET<sub>t</sub> | TOP<sub>lt</sub> |   OLS    |
| :-------------: | :--------------: | :-------------: | :--------------: | :------: |
| 28.60 | 4.14 | 48.64 | 20.26 | 35.65 |

We appreciate your patience and understanding.
