### ISSUE TITLE
one issue of different performance

### ISSUE THREAD

**Issue by laniuros** [OpenDriveLab/TopoNet#9]
In commit 07773fc, the DET_l score changed from 22.1 to 28.5. Was that due to an update in the evaluation function or a change in your configuration? Looking forward for your reply

**Comment by sephyli** [comment]
The change in the DET_l score was due to an adjustment in our configuration, where we increased the regression loss weight for better model convergence. Following this discovery, we took the necessary steps to update all our experiments to reflect this improvement and subsequently revised the paper to incorporate these latest results.

**Comment by laniuros** [comment]
you mean the loss weight 0.025 of loss bbox?

**Comment by sephyli** [comment]
Yes, we changed it from 0.0075 to 0.025.
